services:
  code:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: webdav-play-code
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - db